<table>
	<?php for ($y = $world->getHeight(); $y >= 0; $y--): ?>
		<tr>
			<td><?=$y?></td>
			<?php for ($x = 0; $x <= $world->getWidth(); $x++): ?>
				<td>
					<?php foreach ($world->getAllAnimals() as $object): ?>
						<?php if ($object->getX() == $x and $object->getY() == $y): ?>
							<?=$object->getSymbol()?>
						<?php endif; ?>
					<?php endforeach; ?>
				</td>
			<?php endfor; ?> 
		</tr>
	<?php endfor; ?>
</table>